- slug: nutrkeratina
  title: Nutrikeratina
  description: |
    Crema para peinar con keratina. Nutre intensamente el cabello otorgándole máxima hidratación y brillo. Recarga queratínica que aporta protección a los cabellos secos, muy secos y rebeldes.

    La fórmula de Nutrikeratina refuerza la fibra capilar protegiendo la estructura natural del cabello. Modela sin apelmazar. Suaviza el cabello facilitando el peinado.
  type:
    - 250 ml
    - 100 ml

- slug: aaa
  title: AAAA
  description: |
   Lorem ipsum dolor sit amet, consectetur adipisicing elit. Et harum beatae pariatur, possimus in autem porro suscipit necessitatibus soluta quaerat, unde quae consequuntur, vitae similique ipsa perferendis incidunt, voluptate inventore?
  type:
    - 1 ml
    - 2 ml

